# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: debug
      run: echo "$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
    - name: Make artifact folder
      run: mkdir /Test-Build-NET
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./UltrakillSaveEditor/UltrakillSaveEditor.csproj --property:OutputPath="/Test-Build-NET" --no-restore
    - name: Test
      run: dotnet test ./UltrakillSaveEditor/UltrakillSaveEditor.csproj --logger trx --property:OutputPath="/Test-Build-NET"
    - name: Upload .NET build results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results
        path: /Test-Build-NET
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
